[package]
name = "issuing"
description = "An easy-to-use customizable error type"
version = "3.0.0"
edition = "2024"
rust-version = "1.99"
categories = ["data-structures", "no-std::no-alloc", "rust-patterns", "value-formatting", "development-tools::debugging"]
keywords = ["issue", "error", "cli"]
repository = "https://github.com/alejandro-vaz/issuing"
license = "MIT"
authors = ["Alejandro Vaz <alejandro.vaz.myt@gmail.com>"]

[lib]
path = "./lib.rs"

[[test]]
name = "issuing"
path = "tests.rs"

[dependencies]
enum_dispatch = "0.3"
